pipeline {

      environment {
        registry = "vanessakovalsky/my-image-python"
        registryCredential = 'docker'
      }

    agent {
        docker {
            image 'python'
        }
    }
      stages {
        stage('Clone sources') {
            steps {
                git url: 'https://github.com/vanessakovalsky/python-api-handle-it.git'
            }
        }
            stage('Security analysis') {
		        agent any
                  steps{
				sh "docker run --rm --volume \$(pwd) secfigo/bandit:latest"
			}
		}
		stage ("Dependency Check with Python Safety"){
			steps{
				catchError {
					sh "docker run --rm --volume \$(pwd) pyupio/safety:latest safety check"
					sh "docker run --rm --volume \$(pwd) pyupio/safety:latest safety check --json > report.json"
				}
				echo currentBuild.result
			}
		}
		stage ("Static Analysis with python-taint"){
			steps{
				sh "docker run --rm --volume \$(pwd) vickyrajagopal/python-taint-docker pyt ."
			}
		}

        stage('continuous integration') { // Compile and do unit testing

             tools {
               gradle 'installGradle'
             }
             steps {
                 parallel (
                 // run Gradle to execute compile and unit testing
                    pylint: {
                        sh 'cd continuous-integration && gradle lint'
                    },
                    pycode: {
                        sh 'cd continuous-integration && gradle pycode'
                    }
                )
             }
           }*/

        // stage('testcode') {
            //  tools {
            //    gradle 'installGradle'
            //  }
        //     steps {
        //         sh 'gradle test'
        //     }
        // }
        
        /*stage('Package and deploy') {
             tools {
               gradle 'installGradle'
             }
            steps {
                sh 'cd continuous-integration && gradle up'
            }
        }*/

        stage('Build docker image') {
            steps{
                script {
                    dockerImage = docker.build registry + ":$BUILD_NUMBER"
                } 
            }       
        }

        stage('Push Image') {
            steps{
                script {
                    docker.withRegistry( '', registryCredential ) {
                        dockerImage.push("$BUILD_NUMBER")
                    }
                }
            }
        }

        stage('Test image docker') {
            steps {
                sh 'docker run -d --name my-image-python -p 3002:3002 --rm vanessakovalsky/my-image-python'
            }
        }

       /* stage('Deploy to environment') {
            steps {
                sh 'ansible-playbook -i vagrant/k8s-ansible/inventory vagrant/k8s-ansible/k8s-deployment.yml'
            }
        }*/
      }
 }
